
services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: medilabo-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: medilabo
    volumes:
      - mongo-data:/data/db
    networks:
      - medilabo-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/medilabo --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Patient Microservice
  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: medilabo-patient-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:secret@mongodb:27017/medilabo?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - medilabo-network

  # Note Microservice (Sprint 2)
  note-service:
    build:
      context: ./note-service
      dockerfile: Dockerfile
    container_name: medilabo-note-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:secret@mongodb:27017/medilabo?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - medilabo-network

  # Risk Assessment Service (Sprint 3)
  risk-service:
    build:
      context: ./risk-service
      dockerfile: Dockerfile
    container_name: medilabo-risk-service
    ports:
      - "8083:8083"
    environment:
      - PATIENT_SERVICE_URL=http://patient-service:8081
      - NOTE_SERVICE_URL=http://note-service:8082
    depends_on:
      - patient-service
      - note-service
    networks:
      - medilabo-network

  # API Gateway
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: medilabo-gateway
    ports:
      - "8080:8080"
    environment:
      - PATIENT_SERVICE_URL=http://patient-service:8081
      - NOTE_SERVICE_URL=http://note-service:8082
      - RISK_SERVICE_URL=http://risk-service:8083
    depends_on:
      - patient-service
      - risk-service
    networks:
      - medilabo-network

  # Frontend (Vue 3 + Vite + Tailwind)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medilabo-frontend
    ports:
      - "80:80"
    depends_on:
      - gateway
    networks:
      - medilabo-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  medilabo-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local

