version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: medilabo-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: medilabo
    volumes:
      - mongo-data:/data/db
    networks:
      - medilabo-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/medilabo --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Patient Microservice (Sprint 1)
  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    container_name: medilabo-patient-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:secret@mongodb:27017/medilabo?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - medilabo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API Gateway (Sprint 1)
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: medilabo-gateway
    ports:
      - "8080:8080"
    environment:
      - PATIENT_SERVICE_URL=http://patient-service:8081
      - NOTE_SERVICE_URL=http://note-service:8082
      - RISK_SERVICE_URL=http://risk-service:8083
    depends_on:
      patient-service:
        condition: service_healthy
    networks:
      - medilabo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  medilabo-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local

